// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: v1/pipe/pipeline_cache.proto

package pipe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PipelineCaches struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"cache_build" yaml:"cache_build"
	CacheBuild []*PipelineCache `protobuf:"bytes,1,rep,name=cache_build,json=cacheBuild,proto3" json:"cache_build" yaml:"cache_build"`
	// @gotags: json:"cache_dependent" yaml:"cache_dependent"
	CacheDependent []*PipelineCache `protobuf:"bytes,2,rep,name=cache_dependent,json=cacheDependent,proto3" json:"cache_dependent" yaml:"cache_dependent"`
	// @gotags: json:"cache_product" yaml:"cache_product"
	CacheProduct []*PipelineCache `protobuf:"bytes,3,rep,name=cache_product,json=cacheProduct,proto3" json:"cache_product" yaml:"cache_product"`
}

func (x *PipelineCaches) Reset() {
	*x = PipelineCaches{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pipe_pipeline_cache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineCaches) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCaches) ProtoMessage() {}

func (x *PipelineCaches) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pipe_pipeline_cache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCaches.ProtoReflect.Descriptor instead.
func (*PipelineCaches) Descriptor() ([]byte, []int) {
	return file_v1_pipe_pipeline_cache_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineCaches) GetCacheBuild() []*PipelineCache {
	if x != nil {
		return x.CacheBuild
	}
	return nil
}

func (x *PipelineCaches) GetCacheDependent() []*PipelineCache {
	if x != nil {
		return x.CacheDependent
	}
	return nil
}

func (x *PipelineCaches) GetCacheProduct() []*PipelineCache {
	if x != nil {
		return x.CacheProduct
	}
	return nil
}

type PipelineCache struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"path" yaml:"path"
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path" yaml:"path"`
	// @gotags: json:"desc" yaml:"desc"
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc" yaml:"desc"`
	// @gotags: json:"is_enable" yaml:"is_enable"
	IsEnable bool `protobuf:"varint,3,opt,name=is_enable,json=isEnable,proto3" json:"is_enable" yaml:"is_enable"`
}

func (x *PipelineCache) Reset() {
	*x = PipelineCache{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pipe_pipeline_cache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCache) ProtoMessage() {}

func (x *PipelineCache) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pipe_pipeline_cache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCache.ProtoReflect.Descriptor instead.
func (*PipelineCache) Descriptor() ([]byte, []int) {
	return file_v1_pipe_pipeline_cache_proto_rawDescGZIP(), []int{1}
}

func (x *PipelineCache) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PipelineCache) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *PipelineCache) GetIsEnable() bool {
	if x != nil {
		return x.IsEnable
	}
	return false
}

var File_v1_pipe_pipeline_cache_proto protoreflect.FileDescriptor

var file_v1_pipe_pipeline_cache_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x76, 0x31, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x22, 0xd6, 0x01, 0x0a,
	0x0e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x73, 0x12,
	0x3c, 0x0a, 0x0b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x70,
	0x69, 0x70, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x0a, 0x63, 0x61, 0x63, 0x68, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x44, 0x0a,
	0x0f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x70, 0x69, 0x70, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x52, 0x0e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x6e, 0x74, 0x12, 0x40, 0x0a, 0x0d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x0c, 0x63, 0x61, 0x63, 0x68, 0x65, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x22, 0x54, 0x0a, 0x0d, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65,
	0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x73, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x6a, 0x2d, 0x73, 0x68, 0x2f,
	0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_pipe_pipeline_cache_proto_rawDescOnce sync.Once
	file_v1_pipe_pipeline_cache_proto_rawDescData = file_v1_pipe_pipeline_cache_proto_rawDesc
)

func file_v1_pipe_pipeline_cache_proto_rawDescGZIP() []byte {
	file_v1_pipe_pipeline_cache_proto_rawDescOnce.Do(func() {
		file_v1_pipe_pipeline_cache_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_pipe_pipeline_cache_proto_rawDescData)
	})
	return file_v1_pipe_pipeline_cache_proto_rawDescData
}

var file_v1_pipe_pipeline_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_pipe_pipeline_cache_proto_goTypes = []interface{}{
	(*PipelineCaches)(nil), // 0: meta.v1.pipe.PipelineCaches
	(*PipelineCache)(nil),  // 1: meta.v1.pipe.PipelineCache
}
var file_v1_pipe_pipeline_cache_proto_depIdxs = []int32{
	1, // 0: meta.v1.pipe.PipelineCaches.cache_build:type_name -> meta.v1.pipe.PipelineCache
	1, // 1: meta.v1.pipe.PipelineCaches.cache_dependent:type_name -> meta.v1.pipe.PipelineCache
	1, // 2: meta.v1.pipe.PipelineCaches.cache_product:type_name -> meta.v1.pipe.PipelineCache
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_pipe_pipeline_cache_proto_init() }
func file_v1_pipe_pipeline_cache_proto_init() {
	if File_v1_pipe_pipeline_cache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_pipe_pipeline_cache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineCaches); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pipe_pipeline_cache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineCache); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_pipe_pipeline_cache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_pipe_pipeline_cache_proto_goTypes,
		DependencyIndexes: file_v1_pipe_pipeline_cache_proto_depIdxs,
		MessageInfos:      file_v1_pipe_pipeline_cache_proto_msgTypes,
	}.Build()
	File_v1_pipe_pipeline_cache_proto = out.File
	file_v1_pipe_pipeline_cache_proto_rawDesc = nil
	file_v1_pipe_pipeline_cache_proto_goTypes = nil
	file_v1_pipe_pipeline_cache_proto_depIdxs = nil
}
