// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: v1/pipe/pipeline_job.proto

package pipe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PipelineJobTerm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"logic" yaml:"logic"
	Logic string `protobuf:"bytes,1,opt,name=logic,proto3" json:"logic" yaml:"logic"`
	// @gotags: json:"terms_key" yaml:"terms_key"
	TermsKey string `protobuf:"bytes,2,opt,name=terms_key,json=termsKey,proto3" json:"terms_key" yaml:"terms_key"`
	// @gotags: json:"terms" yaml:"terms"
	Terms string `protobuf:"bytes,3,opt,name=terms,proto3" json:"terms" yaml:"terms"`
	// @gotags: json:"terms_value" yaml:"terms_value"
	TermsValue string `protobuf:"bytes,4,opt,name=terms_value,json=termsValue,proto3" json:"terms_value" yaml:"terms_value"`
}

func (x *PipelineJobTerm) Reset() {
	*x = PipelineJobTerm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pipe_pipeline_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineJobTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineJobTerm) ProtoMessage() {}

func (x *PipelineJobTerm) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pipe_pipeline_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineJobTerm.ProtoReflect.Descriptor instead.
func (*PipelineJobTerm) Descriptor() ([]byte, []int) {
	return file_v1_pipe_pipeline_job_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineJobTerm) GetLogic() string {
	if x != nil {
		return x.Logic
	}
	return ""
}

func (x *PipelineJobTerm) GetTermsKey() string {
	if x != nil {
		return x.TermsKey
	}
	return ""
}

func (x *PipelineJobTerm) GetTerms() string {
	if x != nil {
		return x.Terms
	}
	return ""
}

func (x *PipelineJobTerm) GetTermsValue() string {
	if x != nil {
		return x.TermsValue
	}
	return ""
}

type PipelineJobOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"label" yaml:"label"
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label" yaml:"label"`
	// @gotags: json:"field" yaml:"field"
	Field string `protobuf:"bytes,2,opt,name=field,proto3" json:"field" yaml:"field"`
}

func (x *PipelineJobOut) Reset() {
	*x = PipelineJobOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pipe_pipeline_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineJobOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineJobOut) ProtoMessage() {}

func (x *PipelineJobOut) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pipe_pipeline_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineJobOut.ProtoReflect.Descriptor instead.
func (*PipelineJobOut) Descriptor() ([]byte, []int) {
	return file_v1_pipe_pipeline_job_proto_rawDescGZIP(), []int{1}
}

func (x *PipelineJobOut) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PipelineJobOut) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type PipelineJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"job_id" yaml:"job_id"
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id" yaml:"job_id"`
	// @gotags: json:"job_name" yaml:"job_name"
	JobName string `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name" yaml:"job_name"`
	// @gotags: json:"job_effect" yaml:"job_effect"
	JobEffect JobEffect `protobuf:"varint,3,opt,name=job_effect,json=jobEffect,proto3,enum=meta.v1.pipe.JobEffect" json:"job_effect" yaml:"job_effect"`
	// @gotags: json:"suite_code" yaml:"suite_code"
	SuiteCode string `protobuf:"bytes,4,opt,name=suite_code,json=suiteCode,proto3" json:"suite_code" yaml:"suite_code"`
	// @gotags: json:"node_position" yaml:"node_position"
	NodePosition string `protobuf:"bytes,5,opt,name=node_position,json=nodePosition,proto3" json:"node_position" yaml:"node_position"`
	// @gotags: json:"node_name" yaml:"node_name"
	NodeName string `protobuf:"bytes,6,opt,name=node_name,json=nodeName,proto3" json:"node_name" yaml:"node_name"`
	// @gotags: json:"node_type" yaml:"node_type"
	NodeType string `protobuf:"bytes,7,opt,name=node_type,json=nodeType,proto3" json:"node_type" yaml:"node_type"`
	// @gotags: json:"prev" yaml:"prev"
	Prev []string `protobuf:"bytes,8,rep,name=prev,proto3" json:"prev" yaml:"prev"`
	// @gotags: json:"next" yaml:"next"
	Next []string `protobuf:"bytes,9,rep,name=next,proto3" json:"next" yaml:"next"`
	// @gotags: json:"param" yaml:"param"
	Param string `protobuf:"bytes,10,opt,name=param,proto3" json:"param" yaml:"param"`
	// @gotags: json:"terms" yaml:"terms"
	Terms []*PipelineJobTerm `protobuf:"bytes,11,rep,name=terms,proto3" json:"terms" yaml:"terms"`
	// @gotags: json:"outs" yaml:"outs"
	Outs []*PipelineJobOut `protobuf:"bytes,12,rep,name=outs,proto3" json:"outs" yaml:"outs"`
	// @gotags: json:"no_run" yaml:"no_run"
	NoRun bool `protobuf:"varint,13,opt,name=no_run,json=noRun,proto3" json:"no_run" yaml:"no_run"`
	// @gotags: json:"suite_func" yaml:"suite_func"
	SuiteFunc string `protobuf:"bytes,14,opt,name=suite_func,json=suiteFunc,proto3" json:"suite_func" yaml:"suite_func"`
}

func (x *PipelineJob) Reset() {
	*x = PipelineJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pipe_pipeline_job_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineJob) ProtoMessage() {}

func (x *PipelineJob) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pipe_pipeline_job_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineJob.ProtoReflect.Descriptor instead.
func (*PipelineJob) Descriptor() ([]byte, []int) {
	return file_v1_pipe_pipeline_job_proto_rawDescGZIP(), []int{2}
}

func (x *PipelineJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PipelineJob) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *PipelineJob) GetJobEffect() JobEffect {
	if x != nil {
		return x.JobEffect
	}
	return JobEffect_EFFECT_UNKNOWN
}

func (x *PipelineJob) GetSuiteCode() string {
	if x != nil {
		return x.SuiteCode
	}
	return ""
}

func (x *PipelineJob) GetNodePosition() string {
	if x != nil {
		return x.NodePosition
	}
	return ""
}

func (x *PipelineJob) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PipelineJob) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *PipelineJob) GetPrev() []string {
	if x != nil {
		return x.Prev
	}
	return nil
}

func (x *PipelineJob) GetNext() []string {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *PipelineJob) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *PipelineJob) GetTerms() []*PipelineJobTerm {
	if x != nil {
		return x.Terms
	}
	return nil
}

func (x *PipelineJob) GetOuts() []*PipelineJobOut {
	if x != nil {
		return x.Outs
	}
	return nil
}

func (x *PipelineJob) GetNoRun() bool {
	if x != nil {
		return x.NoRun
	}
	return false
}

func (x *PipelineJob) GetSuiteFunc() string {
	if x != nil {
		return x.SuiteFunc
	}
	return ""
}

var File_v1_pipe_pipeline_job_proto protoreflect.FileDescriptor

var file_v1_pipe_pipeline_job_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x76, 0x31, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x5f, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x1a, 0x17, 0x76, 0x31, 0x2f, 0x70,
	0x69, 0x70, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x70, 0x69, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x0f, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x4a,
	0x6f, 0x62, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x65, 0x72, 0x6d, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x65, 0x72,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x3c, 0x0a, 0x0e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x4a, 0x6f, 0x62, 0x4f,
	0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0xd0,
	0x03, 0x0a, 0x0b, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x4a, 0x6f, 0x62, 0x12, 0x15,
	0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x36, 0x0a, 0x0a, 0x6a, 0x6f, 0x62, 0x5f, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x70,
	0x69, 0x70, 0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x52, 0x09, 0x6a,
	0x6f, 0x62, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x75, 0x69, 0x74,
	0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x75,
	0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6e, 0x6f, 0x64, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f,
	0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x72, 0x65, 0x76, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x70, 0x72, 0x65, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65,
	0x78, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x12, 0x33, 0x0a, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x18, 0x0b, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69,
	0x70, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x4a, 0x6f, 0x62, 0x54, 0x65,
	0x72, 0x6d, 0x52, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x12, 0x30, 0x0a, 0x04, 0x6f, 0x75, 0x74,
	0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x4a,
	0x6f, 0x62, 0x4f, 0x75, 0x74, 0x52, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6e,
	0x6f, 0x5f, 0x72, 0x75, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6e, 0x6f, 0x52,
	0x75, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x75, 0x69, 0x74, 0x65, 0x5f, 0x66, 0x75, 0x6e, 0x63,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x69, 0x74, 0x65, 0x46, 0x75, 0x6e,
	0x63, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x7a, 0x6a, 0x2d, 0x73, 0x68, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x69,
	0x70, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_pipe_pipeline_job_proto_rawDescOnce sync.Once
	file_v1_pipe_pipeline_job_proto_rawDescData = file_v1_pipe_pipeline_job_proto_rawDesc
)

func file_v1_pipe_pipeline_job_proto_rawDescGZIP() []byte {
	file_v1_pipe_pipeline_job_proto_rawDescOnce.Do(func() {
		file_v1_pipe_pipeline_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_pipe_pipeline_job_proto_rawDescData)
	})
	return file_v1_pipe_pipeline_job_proto_rawDescData
}

var file_v1_pipe_pipeline_job_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_pipe_pipeline_job_proto_goTypes = []interface{}{
	(*PipelineJobTerm)(nil), // 0: meta.v1.pipe.PipelineJobTerm
	(*PipelineJobOut)(nil),  // 1: meta.v1.pipe.PipelineJobOut
	(*PipelineJob)(nil),     // 2: meta.v1.pipe.PipelineJob
	(JobEffect)(0),          // 3: meta.v1.pipe.JobEffect
}
var file_v1_pipe_pipeline_job_proto_depIdxs = []int32{
	3, // 0: meta.v1.pipe.PipelineJob.job_effect:type_name -> meta.v1.pipe.JobEffect
	0, // 1: meta.v1.pipe.PipelineJob.terms:type_name -> meta.v1.pipe.PipelineJobTerm
	1, // 2: meta.v1.pipe.PipelineJob.outs:type_name -> meta.v1.pipe.PipelineJobOut
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_pipe_pipeline_job_proto_init() }
func file_v1_pipe_pipeline_job_proto_init() {
	if File_v1_pipe_pipeline_job_proto != nil {
		return
	}
	file_v1_pipe_meta_pipe_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_pipe_pipeline_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineJobTerm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pipe_pipeline_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineJobOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pipe_pipeline_job_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_pipe_pipeline_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_pipe_pipeline_job_proto_goTypes,
		DependencyIndexes: file_v1_pipe_pipeline_job_proto_depIdxs,
		MessageInfos:      file_v1_pipe_pipeline_job_proto_msgTypes,
	}.Build()
	File_v1_pipe_pipeline_job_proto = out.File
	file_v1_pipe_pipeline_job_proto_rawDesc = nil
	file_v1_pipe_pipeline_job_proto_goTypes = nil
	file_v1_pipe_pipeline_job_proto_depIdxs = nil
}
