// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: v1/pipe/pipeline_hook.proto

package pipe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PipelineHook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"webhook_enable" yaml:"webhook_enable"
	WebhookEnable bool `protobuf:"varint,1,opt,name=webhook_enable,json=webhookEnable,proto3" json:"webhook_enable" yaml:"webhook_enable"`
	// @gotags: json:"webhook_uri" yaml:"webhook_uri"
	WebhookUri string `protobuf:"bytes,2,opt,name=webhook_uri,json=webhookUri,proto3" json:"webhook_uri" yaml:"webhook_uri"`
	// @gotags: json:"api_enable" yaml:"api_enable"
	ApiEnable bool `protobuf:"varint,3,opt,name=api_enable,json=apiEnable,proto3" json:"api_enable" yaml:"api_enable"`
	// @gotags: json:"api_actions" yaml:"api_actions"
	ApiActions []string `protobuf:"bytes,4,rep,name=api_actions,json=apiActions,proto3" json:"api_actions" yaml:"api_actions"`
	// @gotags: json:"cron_enable" yaml:"cron_enable"
	CronEnable bool `protobuf:"varint,5,opt,name=cron_enable,json=cronEnable,proto3" json:"cron_enable" yaml:"cron_enable"`
	// @gotags: json:"cron_mode" yaml:"cron_mode"
	CronMode string `protobuf:"bytes,6,opt,name=cron_mode,json=cronMode,proto3" json:"cron_mode" yaml:"cron_mode"`
	// @gotags: json:"cron_expression" yaml:"cron_expression"
	CronExpression string `protobuf:"bytes,7,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression" yaml:"cron_expression"`
	// @gotags: json:"cron_reset_on_run" yaml:"cron_reset_on_run"
	CronResetOnRun bool `protobuf:"varint,8,opt,name=cron_reset_on_run,json=cronResetOnRun,proto3" json:"cron_reset_on_run" yaml:"cron_reset_on_run"`
}

func (x *PipelineHook) Reset() {
	*x = PipelineHook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pipe_pipeline_hook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineHook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineHook) ProtoMessage() {}

func (x *PipelineHook) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pipe_pipeline_hook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineHook.ProtoReflect.Descriptor instead.
func (*PipelineHook) Descriptor() ([]byte, []int) {
	return file_v1_pipe_pipeline_hook_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineHook) GetWebhookEnable() bool {
	if x != nil {
		return x.WebhookEnable
	}
	return false
}

func (x *PipelineHook) GetWebhookUri() string {
	if x != nil {
		return x.WebhookUri
	}
	return ""
}

func (x *PipelineHook) GetApiEnable() bool {
	if x != nil {
		return x.ApiEnable
	}
	return false
}

func (x *PipelineHook) GetApiActions() []string {
	if x != nil {
		return x.ApiActions
	}
	return nil
}

func (x *PipelineHook) GetCronEnable() bool {
	if x != nil {
		return x.CronEnable
	}
	return false
}

func (x *PipelineHook) GetCronMode() string {
	if x != nil {
		return x.CronMode
	}
	return ""
}

func (x *PipelineHook) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *PipelineHook) GetCronResetOnRun() bool {
	if x != nil {
		return x.CronResetOnRun
	}
	return false
}

var File_v1_pipe_pipeline_hook_proto protoreflect.FileDescriptor

var file_v1_pipe_pipeline_hook_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x76, 0x31, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x5f, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d,
	0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x22, 0xa8, 0x02, 0x0a, 0x0c,
	0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x48, 0x6f, 0x6f, 0x6b, 0x12, 0x25, 0x0a, 0x0e,
	0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x75,
	0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f,
	0x6b, 0x55, 0x72, 0x69, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x5f, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x70, 0x69, 0x45, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x69, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x69, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x6f, 0x6e, 0x5f, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x63, 0x72, 0x6f, 0x6e, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x72, 0x6f, 0x6e, 0x5f, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x6f, 0x6e, 0x4d, 0x6f,
	0x64, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x72, 0x6f, 0x6e, 0x5f, 0x65, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x72, 0x6f,
	0x6e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x11, 0x63,
	0x72, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x74, 0x5f, 0x6f, 0x6e, 0x5f, 0x72, 0x75, 0x6e,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x63, 0x72, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x65,
	0x74, 0x4f, 0x6e, 0x52, 0x75, 0x6e, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x6a, 0x2d, 0x73, 0x68, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_pipe_pipeline_hook_proto_rawDescOnce sync.Once
	file_v1_pipe_pipeline_hook_proto_rawDescData = file_v1_pipe_pipeline_hook_proto_rawDesc
)

func file_v1_pipe_pipeline_hook_proto_rawDescGZIP() []byte {
	file_v1_pipe_pipeline_hook_proto_rawDescOnce.Do(func() {
		file_v1_pipe_pipeline_hook_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_pipe_pipeline_hook_proto_rawDescData)
	})
	return file_v1_pipe_pipeline_hook_proto_rawDescData
}

var file_v1_pipe_pipeline_hook_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_pipe_pipeline_hook_proto_goTypes = []interface{}{
	(*PipelineHook)(nil), // 0: meta.v1.pipe.PipelineHook
}
var file_v1_pipe_pipeline_hook_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_pipe_pipeline_hook_proto_init() }
func file_v1_pipe_pipeline_hook_proto_init() {
	if File_v1_pipe_pipeline_hook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_pipe_pipeline_hook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineHook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_pipe_pipeline_hook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_pipe_pipeline_hook_proto_goTypes,
		DependencyIndexes: file_v1_pipe_pipeline_hook_proto_depIdxs,
		MessageInfos:      file_v1_pipe_pipeline_hook_proto_msgTypes,
	}.Build()
	File_v1_pipe_pipeline_hook_proto = out.File
	file_v1_pipe_pipeline_hook_proto_rawDesc = nil
	file_v1_pipe_pipeline_hook_proto_goTypes = nil
	file_v1_pipe_pipeline_hook_proto_depIdxs = nil
}
