// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: v1/pipe/pipeline_role.proto

package pipe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PipelineRoles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"allow_all_corp" yaml:"allow_all_corp"
	AllowAllCorp bool `protobuf:"varint,1,opt,name=allow_all_corp,json=allowAllCorp,proto3" json:"allow_all_corp" yaml:"allow_all_corp"`
	// @gotags: json:"roles" yaml:"roles"
	Roles []*PipelineRole `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles" yaml:"roles"`
}

func (x *PipelineRoles) Reset() {
	*x = PipelineRoles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pipe_pipeline_role_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineRoles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineRoles) ProtoMessage() {}

func (x *PipelineRoles) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pipe_pipeline_role_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineRoles.ProtoReflect.Descriptor instead.
func (*PipelineRoles) Descriptor() ([]byte, []int) {
	return file_v1_pipe_pipeline_role_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineRoles) GetAllowAllCorp() bool {
	if x != nil {
		return x.AllowAllCorp
	}
	return false
}

func (x *PipelineRoles) GetRoles() []*PipelineRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

type PipelineRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"role_type" yaml:"role_type"
	RoleType string `protobuf:"bytes,1,opt,name=role_type,json=roleType,proto3" json:"role_type" yaml:"role_type"`
	// @gotags: json:"role_code" yaml:"role_code"
	RoleCode string `protobuf:"bytes,2,opt,name=role_code,json=roleCode,proto3" json:"role_code" yaml:"role_code"`
	// @gotags: json:"allow_run" yaml:"allow_run"
	AllowRun bool `protobuf:"varint,3,opt,name=allow_run,json=allowRun,proto3" json:"allow_run" yaml:"allow_run"`
	// @gotags: json:"allow_edit" yaml:"allow_edit"
	AllowEdit bool `protobuf:"varint,4,opt,name=allow_edit,json=allowEdit,proto3" json:"allow_edit" yaml:"allow_edit"`
	// @gotags: json:"allow_delete" yaml:"allow_delete"
	AllowDelete bool `protobuf:"varint,5,opt,name=allow_delete,json=allowDelete,proto3" json:"allow_delete" yaml:"allow_delete"`
	// @gotags: json:"allow_share" yaml:"allow_share"
	AllowShare bool `protobuf:"varint,6,opt,name=allow_share,json=allowShare,proto3" json:"allow_share" yaml:"allow_share"`
}

func (x *PipelineRole) Reset() {
	*x = PipelineRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pipe_pipeline_role_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineRole) ProtoMessage() {}

func (x *PipelineRole) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pipe_pipeline_role_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineRole.ProtoReflect.Descriptor instead.
func (*PipelineRole) Descriptor() ([]byte, []int) {
	return file_v1_pipe_pipeline_role_proto_rawDescGZIP(), []int{1}
}

func (x *PipelineRole) GetRoleType() string {
	if x != nil {
		return x.RoleType
	}
	return ""
}

func (x *PipelineRole) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *PipelineRole) GetAllowRun() bool {
	if x != nil {
		return x.AllowRun
	}
	return false
}

func (x *PipelineRole) GetAllowEdit() bool {
	if x != nil {
		return x.AllowEdit
	}
	return false
}

func (x *PipelineRole) GetAllowDelete() bool {
	if x != nil {
		return x.AllowDelete
	}
	return false
}

func (x *PipelineRole) GetAllowShare() bool {
	if x != nil {
		return x.AllowShare
	}
	return false
}

var File_v1_pipe_pipeline_role_proto protoreflect.FileDescriptor

var file_v1_pipe_pipeline_role_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x76, 0x31, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d,
	0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x22, 0x67, 0x0a, 0x0d, 0x50,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0e,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x63, 0x6f, 0x72, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x43, 0x6f,
	0x72, 0x70, 0x12, 0x30, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65,
	0x2e, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x05, 0x72,
	0x6f, 0x6c, 0x65, 0x73, 0x22, 0xc8, 0x01, 0x0a, 0x0c, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x72, 0x75, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x75, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x65, 0x64, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x45, 0x64, 0x69, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42,
	0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x6a,
	0x2d, 0x73, 0x68, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x69, 0x70, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_pipe_pipeline_role_proto_rawDescOnce sync.Once
	file_v1_pipe_pipeline_role_proto_rawDescData = file_v1_pipe_pipeline_role_proto_rawDesc
)

func file_v1_pipe_pipeline_role_proto_rawDescGZIP() []byte {
	file_v1_pipe_pipeline_role_proto_rawDescOnce.Do(func() {
		file_v1_pipe_pipeline_role_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_pipe_pipeline_role_proto_rawDescData)
	})
	return file_v1_pipe_pipeline_role_proto_rawDescData
}

var file_v1_pipe_pipeline_role_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_pipe_pipeline_role_proto_goTypes = []interface{}{
	(*PipelineRoles)(nil), // 0: meta.v1.pipe.PipelineRoles
	(*PipelineRole)(nil),  // 1: meta.v1.pipe.PipelineRole
}
var file_v1_pipe_pipeline_role_proto_depIdxs = []int32{
	1, // 0: meta.v1.pipe.PipelineRoles.roles:type_name -> meta.v1.pipe.PipelineRole
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_pipe_pipeline_role_proto_init() }
func file_v1_pipe_pipeline_role_proto_init() {
	if File_v1_pipe_pipeline_role_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_pipe_pipeline_role_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineRoles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pipe_pipeline_role_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_pipe_pipeline_role_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_pipe_pipeline_role_proto_goTypes,
		DependencyIndexes: file_v1_pipe_pipeline_role_proto_depIdxs,
		MessageInfos:      file_v1_pipe_pipeline_role_proto_msgTypes,
	}.Build()
	File_v1_pipe_pipeline_role_proto = out.File
	file_v1_pipe_pipeline_role_proto_rawDesc = nil
	file_v1_pipe_pipeline_role_proto_goTypes = nil
	file_v1_pipe_pipeline_role_proto_depIdxs = nil
}
