// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: v1/envs/meta.proto

package envs

import (
	pipe "github.com/zj-sh/meta/v1/pipe"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayType int32

const (
	GatewayType_GATEWAY_TYPE_UNKNOWN GatewayType = 0
	GatewayType_INGRESS              GatewayType = 1
	GatewayType_EGRESS               GatewayType = 2
	GatewayType_HIGRESS              GatewayType = 3
)

// Enum value maps for GatewayType.
var (
	GatewayType_name = map[int32]string{
		0: "GATEWAY_TYPE_UNKNOWN",
		1: "INGRESS",
		2: "EGRESS",
		3: "HIGRESS",
	}
	GatewayType_value = map[string]int32{
		"GATEWAY_TYPE_UNKNOWN": 0,
		"INGRESS":              1,
		"EGRESS":               2,
		"HIGRESS":              3,
	}
)

func (x GatewayType) Enum() *GatewayType {
	p := new(GatewayType)
	*p = x
	return p
}

func (x GatewayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GatewayType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_envs_meta_proto_enumTypes[0].Descriptor()
}

func (GatewayType) Type() protoreflect.EnumType {
	return &file_v1_envs_meta_proto_enumTypes[0]
}

func (x GatewayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GatewayType.Descriptor instead.
func (GatewayType) EnumDescriptor() ([]byte, []int) {
	return file_v1_envs_meta_proto_rawDescGZIP(), []int{0}
}

type Env struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvId       string      `protobuf:"bytes,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	EnvName     string      `protobuf:"bytes,2,opt,name=env_name,json=envName,proto3" json:"env_name,omitempty"`
	EnvCode     string      `protobuf:"bytes,3,opt,name=env_code,json=envCode,proto3" json:"env_code,omitempty"`
	ProjectId   string      `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceId   string      `protobuf:"bytes,5,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ClusterId   string      `protobuf:"bytes,6,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Namespace   string      `protobuf:"bytes,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AllowTest   bool        `protobuf:"varint,8,opt,name=allow_test,json=allowTest,proto3" json:"allow_test,omitempty"`
	GatewayType GatewayType `protobuf:"varint,9,opt,name=gateway_type,json=gatewayType,proto3,enum=meta.v1.envs.GatewayType" json:"gateway_type,omitempty"`
	EnvPods     []*EnvPod   `protobuf:"bytes,10,rep,name=env_pods,json=envPods,proto3" json:"env_pods,omitempty"`
	EnvVars     []*pipe.Var `protobuf:"bytes,11,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	EnvDesc     string      `protobuf:"bytes,12,opt,name=env_desc,json=envDesc,proto3" json:"env_desc,omitempty"`
}

func (x *Env) Reset() {
	*x = Env{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_envs_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Env) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Env) ProtoMessage() {}

func (x *Env) ProtoReflect() protoreflect.Message {
	mi := &file_v1_envs_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Env.ProtoReflect.Descriptor instead.
func (*Env) Descriptor() ([]byte, []int) {
	return file_v1_envs_meta_proto_rawDescGZIP(), []int{0}
}

func (x *Env) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *Env) GetEnvName() string {
	if x != nil {
		return x.EnvName
	}
	return ""
}

func (x *Env) GetEnvCode() string {
	if x != nil {
		return x.EnvCode
	}
	return ""
}

func (x *Env) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Env) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Env) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Env) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Env) GetAllowTest() bool {
	if x != nil {
		return x.AllowTest
	}
	return false
}

func (x *Env) GetGatewayType() GatewayType {
	if x != nil {
		return x.GatewayType
	}
	return GatewayType_GATEWAY_TYPE_UNKNOWN
}

func (x *Env) GetEnvPods() []*EnvPod {
	if x != nil {
		return x.EnvPods
	}
	return nil
}

func (x *Env) GetEnvVars() []*pipe.Var {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *Env) GetEnvDesc() string {
	if x != nil {
		return x.EnvDesc
	}
	return ""
}

type EnvPod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *EnvPod) Reset() {
	*x = EnvPod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_envs_meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvPod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvPod) ProtoMessage() {}

func (x *EnvPod) ProtoReflect() protoreflect.Message {
	mi := &file_v1_envs_meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvPod.ProtoReflect.Descriptor instead.
func (*EnvPod) Descriptor() ([]byte, []int) {
	return file_v1_envs_meta_proto_rawDescGZIP(), []int{1}
}

func (x *EnvPod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvPod) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

var File_v1_envs_meta_proto protoreflect.FileDescriptor

var file_v1_envs_meta_proto_rawDesc = []byte{
	0x0a, 0x12, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x76, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x65, 0x6e,
	0x76, 0x73, 0x1a, 0x1b, 0x76, 0x31, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x2f, 0x70, 0x69, 0x70, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x76, 0x61, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa4, 0x03, 0x0a, 0x03, 0x45, 0x6e, 0x76, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x76, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x6e, 0x76, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x6e, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x76,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x76,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x54, 0x65, 0x73, 0x74, 0x12, 0x3c,
	0x0a, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x65,
	0x6e, 0x76, 0x73, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a, 0x08,
	0x65, 0x6e, 0x76, 0x5f, 0x70, 0x6f, 0x64, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x65, 0x6e, 0x76, 0x73, 0x2e, 0x45, 0x6e,
	0x76, 0x50, 0x6f, 0x64, 0x52, 0x07, 0x65, 0x6e, 0x76, 0x50, 0x6f, 0x64, 0x73, 0x12, 0x2c, 0x0a,
	0x08, 0x65, 0x6e, 0x76, 0x5f, 0x76, 0x61, 0x72, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x2e, 0x56,
	0x61, 0x72, 0x52, 0x07, 0x65, 0x6e, 0x76, 0x56, 0x61, 0x72, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x6e, 0x76, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x6e, 0x76, 0x44, 0x65, 0x73, 0x63, 0x22, 0x32, 0x0a, 0x06, 0x45, 0x6e, 0x76, 0x50, 0x6f, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2a, 0x4d, 0x0a, 0x0b, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x47, 0x41, 0x54,
	0x45, 0x57, 0x41, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x45, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x48, 0x49, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x03, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x6a, 0x2d, 0x73, 0x68, 0x2f, 0x6d, 0x65,
	0x74, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x76, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_v1_envs_meta_proto_rawDescOnce sync.Once
	file_v1_envs_meta_proto_rawDescData = file_v1_envs_meta_proto_rawDesc
)

func file_v1_envs_meta_proto_rawDescGZIP() []byte {
	file_v1_envs_meta_proto_rawDescOnce.Do(func() {
		file_v1_envs_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_envs_meta_proto_rawDescData)
	})
	return file_v1_envs_meta_proto_rawDescData
}

var file_v1_envs_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_envs_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_envs_meta_proto_goTypes = []interface{}{
	(GatewayType)(0), // 0: meta.v1.envs.GatewayType
	(*Env)(nil),      // 1: meta.v1.envs.Env
	(*EnvPod)(nil),   // 2: meta.v1.envs.EnvPod
	(*pipe.Var)(nil), // 3: meta.v1.pipe.Var
}
var file_v1_envs_meta_proto_depIdxs = []int32{
	0, // 0: meta.v1.envs.Env.gateway_type:type_name -> meta.v1.envs.GatewayType
	2, // 1: meta.v1.envs.Env.env_pods:type_name -> meta.v1.envs.EnvPod
	3, // 2: meta.v1.envs.Env.env_vars:type_name -> meta.v1.pipe.Var
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_envs_meta_proto_init() }
func file_v1_envs_meta_proto_init() {
	if File_v1_envs_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_envs_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Env); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_envs_meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvPod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_envs_meta_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_envs_meta_proto_goTypes,
		DependencyIndexes: file_v1_envs_meta_proto_depIdxs,
		EnumInfos:         file_v1_envs_meta_proto_enumTypes,
		MessageInfos:      file_v1_envs_meta_proto_msgTypes,
	}.Build()
	File_v1_envs_meta_proto = out.File
	file_v1_envs_meta_proto_rawDesc = nil
	file_v1_envs_meta_proto_goTypes = nil
	file_v1_envs_meta_proto_depIdxs = nil
}
