// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: v1/clust/meta.proto

package clust

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterType int32

const (
	ClusterType_CLUSTER_TYPE_UNKNOWN ClusterType = 0
	ClusterType_CLUSTER_CCE          ClusterType = 1
	ClusterType_CLUSTER_ACK          ClusterType = 2
	ClusterType_CLUSTER_TKE          ClusterType = 3
	ClusterType_CLUSTER_SELF         ClusterType = 4
)

// Enum value maps for ClusterType.
var (
	ClusterType_name = map[int32]string{
		0: "CLUSTER_TYPE_UNKNOWN",
		1: "CLUSTER_CCE",
		2: "CLUSTER_ACK",
		3: "CLUSTER_TKE",
		4: "CLUSTER_SELF",
	}
	ClusterType_value = map[string]int32{
		"CLUSTER_TYPE_UNKNOWN": 0,
		"CLUSTER_CCE":          1,
		"CLUSTER_ACK":          2,
		"CLUSTER_TKE":          3,
		"CLUSTER_SELF":         4,
	}
)

func (x ClusterType) Enum() *ClusterType {
	p := new(ClusterType)
	*p = x
	return p
}

func (x ClusterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_clust_meta_proto_enumTypes[0].Descriptor()
}

func (ClusterType) Type() protoreflect.EnumType {
	return &file_v1_clust_meta_proto_enumTypes[0]
}

func (x ClusterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterType.Descriptor instead.
func (ClusterType) EnumDescriptor() ([]byte, []int) {
	return file_v1_clust_meta_proto_rawDescGZIP(), []int{0}
}

type LinkType int32

const (
	LinkType_LINK_TYPE_UNKNOWN LinkType = 0
	LinkType_LINK_KUBE_CONFIG  LinkType = 1
)

// Enum value maps for LinkType.
var (
	LinkType_name = map[int32]string{
		0: "LINK_TYPE_UNKNOWN",
		1: "LINK_KUBE_CONFIG",
	}
	LinkType_value = map[string]int32{
		"LINK_TYPE_UNKNOWN": 0,
		"LINK_KUBE_CONFIG":  1,
	}
)

func (x LinkType) Enum() *LinkType {
	p := new(LinkType)
	*p = x
	return p
}

func (x LinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_clust_meta_proto_enumTypes[1].Descriptor()
}

func (LinkType) Type() protoreflect.EnumType {
	return &file_v1_clust_meta_proto_enumTypes[1]
}

func (x LinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkType.Descriptor instead.
func (LinkType) EnumDescriptor() ([]byte, []int) {
	return file_v1_clust_meta_proto_rawDescGZIP(), []int{1}
}

type ClusterTypeOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value ClusterType `protobuf:"varint,1,opt,name=value,proto3,enum=meta.v1.clust.ClusterType" json:"value,omitempty"`
	Label string      `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *ClusterTypeOption) Reset() {
	*x = ClusterTypeOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_clust_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterTypeOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterTypeOption) ProtoMessage() {}

func (x *ClusterTypeOption) ProtoReflect() protoreflect.Message {
	mi := &file_v1_clust_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterTypeOption.ProtoReflect.Descriptor instead.
func (*ClusterTypeOption) Descriptor() ([]byte, []int) {
	return file_v1_clust_meta_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterTypeOption) GetValue() ClusterType {
	if x != nil {
		return x.Value
	}
	return ClusterType_CLUSTER_TYPE_UNKNOWN
}

func (x *ClusterTypeOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type LinkTypeOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value LinkType `protobuf:"varint,1,opt,name=value,proto3,enum=meta.v1.clust.LinkType" json:"value,omitempty"`
	Label string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *LinkTypeOption) Reset() {
	*x = LinkTypeOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_clust_meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkTypeOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkTypeOption) ProtoMessage() {}

func (x *LinkTypeOption) ProtoReflect() protoreflect.Message {
	mi := &file_v1_clust_meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkTypeOption.ProtoReflect.Descriptor instead.
func (*LinkTypeOption) Descriptor() ([]byte, []int) {
	return file_v1_clust_meta_proto_rawDescGZIP(), []int{1}
}

func (x *LinkTypeOption) GetValue() LinkType {
	if x != nil {
		return x.Value
	}
	return LinkType_LINK_TYPE_UNKNOWN
}

func (x *LinkTypeOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var File_v1_clust_meta_proto protoreflect.FileDescriptor

var file_v1_clust_meta_proto_rawDesc = []byte{
	0x0a, 0x13, 0x76, 0x31, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x22, 0x5b, 0x0a, 0x11, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x22, 0x55, 0x0a, 0x0e, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x2a, 0x6c, 0x0a, 0x0b, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x4c, 0x55, 0x53, 0x54,
	0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x43, 0x43, 0x45,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x41, 0x43,
	0x4b, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x54,
	0x4b, 0x45, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f,
	0x53, 0x45, 0x4c, 0x46, 0x10, 0x04, 0x2a, 0x37, 0x0a, 0x08, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x49, 0x4e,
	0x4b, 0x5f, 0x4b, 0x55, 0x42, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x10, 0x01, 0x42,
	0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x6a,
	0x2d, 0x73, 0x68, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_clust_meta_proto_rawDescOnce sync.Once
	file_v1_clust_meta_proto_rawDescData = file_v1_clust_meta_proto_rawDesc
)

func file_v1_clust_meta_proto_rawDescGZIP() []byte {
	file_v1_clust_meta_proto_rawDescOnce.Do(func() {
		file_v1_clust_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_clust_meta_proto_rawDescData)
	})
	return file_v1_clust_meta_proto_rawDescData
}

var file_v1_clust_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_clust_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_clust_meta_proto_goTypes = []interface{}{
	(ClusterType)(0),          // 0: meta.v1.clust.ClusterType
	(LinkType)(0),             // 1: meta.v1.clust.LinkType
	(*ClusterTypeOption)(nil), // 2: meta.v1.clust.ClusterTypeOption
	(*LinkTypeOption)(nil),    // 3: meta.v1.clust.LinkTypeOption
}
var file_v1_clust_meta_proto_depIdxs = []int32{
	0, // 0: meta.v1.clust.ClusterTypeOption.value:type_name -> meta.v1.clust.ClusterType
	1, // 1: meta.v1.clust.LinkTypeOption.value:type_name -> meta.v1.clust.LinkType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_clust_meta_proto_init() }
func file_v1_clust_meta_proto_init() {
	if File_v1_clust_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_clust_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterTypeOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_clust_meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkTypeOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_clust_meta_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_clust_meta_proto_goTypes,
		DependencyIndexes: file_v1_clust_meta_proto_depIdxs,
		EnumInfos:         file_v1_clust_meta_proto_enumTypes,
		MessageInfos:      file_v1_clust_meta_proto_msgTypes,
	}.Build()
	File_v1_clust_meta_proto = out.File
	file_v1_clust_meta_proto_rawDesc = nil
	file_v1_clust_meta_proto_goTypes = nil
	file_v1_clust_meta_proto_depIdxs = nil
}
