// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: v1/suite/suite_source_auth.proto

package suite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支持授权的方式
type SourceAuthType int32

const (
	SourceAuthType_AUTH_TYPE_UNKNOWN  SourceAuthType = 0
	SourceAuthType_AUTH_TYPE_OAUTH    SourceAuthType = 1
	SourceAuthType_AUTH_TYPE_PASSWORD SourceAuthType = 2
	SourceAuthType_AUTH_TYPE_TOKEN    SourceAuthType = 3
	SourceAuthType_AUTH_TYPE_SSH      SourceAuthType = 4
)

// Enum value maps for SourceAuthType.
var (
	SourceAuthType_name = map[int32]string{
		0: "AUTH_TYPE_UNKNOWN",
		1: "AUTH_TYPE_OAUTH",
		2: "AUTH_TYPE_PASSWORD",
		3: "AUTH_TYPE_TOKEN",
		4: "AUTH_TYPE_SSH",
	}
	SourceAuthType_value = map[string]int32{
		"AUTH_TYPE_UNKNOWN":  0,
		"AUTH_TYPE_OAUTH":    1,
		"AUTH_TYPE_PASSWORD": 2,
		"AUTH_TYPE_TOKEN":    3,
		"AUTH_TYPE_SSH":      4,
	}
)

func (x SourceAuthType) Enum() *SourceAuthType {
	p := new(SourceAuthType)
	*p = x
	return p
}

func (x SourceAuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceAuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_suite_suite_source_auth_proto_enumTypes[0].Descriptor()
}

func (SourceAuthType) Type() protoreflect.EnumType {
	return &file_v1_suite_suite_source_auth_proto_enumTypes[0]
}

func (x SourceAuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceAuthType.Descriptor instead.
func (SourceAuthType) EnumDescriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{0}
}

// 支持的授权方式选项
type SourceAuthTypeOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string         `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value SourceAuthType `protobuf:"varint,2,opt,name=value,proto3,enum=meta.v1.suite.SourceAuthType" json:"value,omitempty"`
}

func (x *SourceAuthTypeOption) Reset() {
	*x = SourceAuthTypeOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthTypeOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthTypeOption) ProtoMessage() {}

func (x *SourceAuthTypeOption) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthTypeOption.ProtoReflect.Descriptor instead.
func (*SourceAuthTypeOption) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SourceAuthTypeOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SourceAuthTypeOption) GetValue() SourceAuthType {
	if x != nil {
		return x.Value
	}
	return SourceAuthType_AUTH_TYPE_UNKNOWN
}

type SourceAuthTypeOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options []*SourceAuthTypeOption `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	Outs    *OutResponse            `protobuf:"bytes,2,opt,name=outs,proto3" json:"outs,omitempty"`
}

func (x *SourceAuthTypeOptionResponse) Reset() {
	*x = SourceAuthTypeOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthTypeOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthTypeOptionResponse) ProtoMessage() {}

func (x *SourceAuthTypeOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthTypeOptionResponse.ProtoReflect.Descriptor instead.
func (*SourceAuthTypeOptionResponse) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SourceAuthTypeOptionResponse) GetOptions() []*SourceAuthTypeOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SourceAuthTypeOptionResponse) GetOuts() *OutResponse {
	if x != nil {
		return x.Outs
	}
	return nil
}

type SourceAuthRepo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FullName string `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	SshUrl   string `protobuf:"bytes,3,opt,name=sshUrl,proto3" json:"sshUrl,omitempty"`
	Id       string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"` // 用作查询分支或tag：gitlab需要id， gitee需要full_name
}

func (x *SourceAuthRepo) Reset() {
	*x = SourceAuthRepo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthRepo) ProtoMessage() {}

func (x *SourceAuthRepo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthRepo.ProtoReflect.Descriptor instead.
func (*SourceAuthRepo) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SourceAuthRepo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SourceAuthRepo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *SourceAuthRepo) GetSshUrl() string {
	if x != nil {
		return x.SshUrl
	}
	return ""
}

func (x *SourceAuthRepo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SourceAuthBranchTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sha     string `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Date    string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *SourceAuthBranchTag) Reset() {
	*x = SourceAuthBranchTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthBranchTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthBranchTag) ProtoMessage() {}

func (x *SourceAuthBranchTag) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthBranchTag.ProtoReflect.Descriptor instead.
func (*SourceAuthBranchTag) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SourceAuthBranchTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SourceAuthBranchTag) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *SourceAuthBranchTag) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SourceAuthBranchTag) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type SourceAuthCommit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName  string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Message   string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *SourceAuthCommit) Reset() {
	*x = SourceAuthCommit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthCommit) ProtoMessage() {}

func (x *SourceAuthCommit) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthCommit.ProtoReflect.Descriptor instead.
func (*SourceAuthCommit) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SourceAuthCommit) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SourceAuthCommit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SourceAuthCommit) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SourceAuthWebhook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName  string       `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	HookUri   string       `protobuf:"bytes,3,opt,name=hookUri,proto3" json:"hookUri,omitempty"`
	RepoUri   string       `protobuf:"bytes,4,opt,name=repoUri,proto3" json:"repoUri,omitempty"`
	Verify    string       `protobuf:"bytes,5,opt,name=verify,proto3" json:"verify,omitempty"`
	TrigPush  bool         `protobuf:"varint,6,opt,name=trigPush,proto3" json:"trigPush,omitempty"`
	TrigTag   bool         `protobuf:"varint,7,opt,name=trigTag,proto3" json:"trigTag,omitempty"`
	TrigMerge bool         `protobuf:"varint,8,opt,name=trigMerge,proto3" json:"trigMerge,omitempty"`
	Token     string       `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`
	Outs      *OutResponse `protobuf:"bytes,10,opt,name=outs,proto3" json:"outs,omitempty"`
}

func (x *SourceAuthWebhook) Reset() {
	*x = SourceAuthWebhook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthWebhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthWebhook) ProtoMessage() {}

func (x *SourceAuthWebhook) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthWebhook.ProtoReflect.Descriptor instead.
func (*SourceAuthWebhook) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SourceAuthWebhook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SourceAuthWebhook) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *SourceAuthWebhook) GetHookUri() string {
	if x != nil {
		return x.HookUri
	}
	return ""
}

func (x *SourceAuthWebhook) GetRepoUri() string {
	if x != nil {
		return x.RepoUri
	}
	return ""
}

func (x *SourceAuthWebhook) GetVerify() string {
	if x != nil {
		return x.Verify
	}
	return ""
}

func (x *SourceAuthWebhook) GetTrigPush() bool {
	if x != nil {
		return x.TrigPush
	}
	return false
}

func (x *SourceAuthWebhook) GetTrigTag() bool {
	if x != nil {
		return x.TrigTag
	}
	return false
}

func (x *SourceAuthWebhook) GetTrigMerge() bool {
	if x != nil {
		return x.TrigMerge
	}
	return false
}

func (x *SourceAuthWebhook) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SourceAuthWebhook) GetOuts() *OutResponse {
	if x != nil {
		return x.Outs
	}
	return nil
}

// 授权url参数
type SourceAuthParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthType    SourceAuthType `protobuf:"varint,1,opt,name=authType,proto3,enum=meta.v1.suite.SourceAuthType" json:"authType,omitempty"`
	RedirectUri string         `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Code        string         `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Username    string         `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password    string         `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SourceAuthParam) Reset() {
	*x = SourceAuthParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthParam) ProtoMessage() {}

func (x *SourceAuthParam) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthParam.ProtoReflect.Descriptor instead.
func (*SourceAuthParam) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{6}
}

func (x *SourceAuthParam) GetAuthType() SourceAuthType {
	if x != nil {
		return x.AuthType
	}
	return SourceAuthType_AUTH_TYPE_UNKNOWN
}

func (x *SourceAuthParam) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *SourceAuthParam) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SourceAuthParam) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SourceAuthParam) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SourceAuthUriResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri  string       `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Outs *OutResponse `protobuf:"bytes,2,opt,name=outs,proto3" json:"outs,omitempty"`
}

func (x *SourceAuthUriResponse) Reset() {
	*x = SourceAuthUriResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthUriResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthUriResponse) ProtoMessage() {}

func (x *SourceAuthUriResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthUriResponse.ProtoReflect.Descriptor instead.
func (*SourceAuthUriResponse) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{7}
}

func (x *SourceAuthUriResponse) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *SourceAuthUriResponse) GetOuts() *OutResponse {
	if x != nil {
		return x.Outs
	}
	return nil
}

type SourceAuthTokens struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken  string       `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken string       `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	ExpiresIn    int64        `protobuf:"varint,3,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`
	RedirectUri  string       `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"` // refresh token时OAuth模式需要，password不需要
	Outs         *OutResponse `protobuf:"bytes,5,opt,name=outs,proto3" json:"outs,omitempty"`
}

func (x *SourceAuthTokens) Reset() {
	*x = SourceAuthTokens{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthTokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthTokens) ProtoMessage() {}

func (x *SourceAuthTokens) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthTokens.ProtoReflect.Descriptor instead.
func (*SourceAuthTokens) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{8}
}

func (x *SourceAuthTokens) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SourceAuthTokens) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SourceAuthTokens) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *SourceAuthTokens) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *SourceAuthTokens) GetOuts() *OutResponse {
	if x != nil {
		return x.Outs
	}
	return nil
}

type SourceAuthSSHCredential struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Credential string `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	Token      string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SourceAuthSSHCredential) Reset() {
	*x = SourceAuthSSHCredential{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthSSHCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthSSHCredential) ProtoMessage() {}

func (x *SourceAuthSSHCredential) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthSSHCredential.ProtoReflect.Descriptor instead.
func (*SourceAuthSSHCredential) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{9}
}

func (x *SourceAuthSSHCredential) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SourceAuthSSHCredential) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *SourceAuthSSHCredential) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SourceAuthSSHCredentialId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token string       `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Outs  *OutResponse `protobuf:"bytes,3,opt,name=outs,proto3" json:"outs,omitempty"`
}

func (x *SourceAuthSSHCredentialId) Reset() {
	*x = SourceAuthSSHCredentialId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthSSHCredentialId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthSSHCredentialId) ProtoMessage() {}

func (x *SourceAuthSSHCredentialId) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthSSHCredentialId.ProtoReflect.Descriptor instead.
func (*SourceAuthSSHCredentialId) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{10}
}

func (x *SourceAuthSSHCredentialId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SourceAuthSSHCredentialId) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SourceAuthSSHCredentialId) GetOuts() *OutResponse {
	if x != nil {
		return x.Outs
	}
	return nil
}

type SourceAuthRepoQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Token   string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SourceAuthRepoQueryRequest) Reset() {
	*x = SourceAuthRepoQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthRepoQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthRepoQueryRequest) ProtoMessage() {}

func (x *SourceAuthRepoQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthRepoQueryRequest.ProtoReflect.Descriptor instead.
func (*SourceAuthRepoQueryRequest) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{11}
}

func (x *SourceAuthRepoQueryRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SourceAuthRepoQueryRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SourceAuthRepoQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repos []*SourceAuthRepo `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	Outs  *OutResponse      `protobuf:"bytes,2,opt,name=outs,proto3" json:"outs,omitempty"`
}

func (x *SourceAuthRepoQueryResponse) Reset() {
	*x = SourceAuthRepoQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthRepoQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthRepoQueryResponse) ProtoMessage() {}

func (x *SourceAuthRepoQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthRepoQueryResponse.ProtoReflect.Descriptor instead.
func (*SourceAuthRepoQueryResponse) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{12}
}

func (x *SourceAuthRepoQueryResponse) GetRepos() []*SourceAuthRepo {
	if x != nil {
		return x.Repos
	}
	return nil
}

func (x *SourceAuthRepoQueryResponse) GetOuts() *OutResponse {
	if x != nil {
		return x.Outs
	}
	return nil
}

type SourceAuthRepoFullName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullName string `protobuf:"bytes,1,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SourceAuthRepoFullName) Reset() {
	*x = SourceAuthRepoFullName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthRepoFullName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthRepoFullName) ProtoMessage() {}

func (x *SourceAuthRepoFullName) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthRepoFullName.ProtoReflect.Descriptor instead.
func (*SourceAuthRepoFullName) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{13}
}

func (x *SourceAuthRepoFullName) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *SourceAuthRepoFullName) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SourceAuthBranchTagQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BranchTags []*SourceAuthBranchTag `protobuf:"bytes,1,rep,name=branchTags,proto3" json:"branchTags,omitempty"`
	Outs       *OutResponse           `protobuf:"bytes,2,opt,name=outs,proto3" json:"outs,omitempty"`
}

func (x *SourceAuthBranchTagQueryResponse) Reset() {
	*x = SourceAuthBranchTagQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthBranchTagQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthBranchTagQueryResponse) ProtoMessage() {}

func (x *SourceAuthBranchTagQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthBranchTagQueryResponse.ProtoReflect.Descriptor instead.
func (*SourceAuthBranchTagQueryResponse) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{14}
}

func (x *SourceAuthBranchTagQueryResponse) GetBranchTags() []*SourceAuthBranchTag {
	if x != nil {
		return x.BranchTags
	}
	return nil
}

func (x *SourceAuthBranchTagQueryResponse) GetOuts() *OutResponse {
	if x != nil {
		return x.Outs
	}
	return nil
}

type SourceAuthCommitQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commits []*SourceAuthCommit `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	Outs    *OutResponse        `protobuf:"bytes,2,opt,name=outs,proto3" json:"outs,omitempty"`
}

func (x *SourceAuthCommitQueryResponse) Reset() {
	*x = SourceAuthCommitQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_source_auth_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceAuthCommitQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceAuthCommitQueryResponse) ProtoMessage() {}

func (x *SourceAuthCommitQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_source_auth_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceAuthCommitQueryResponse.ProtoReflect.Descriptor instead.
func (*SourceAuthCommitQueryResponse) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_source_auth_proto_rawDescGZIP(), []int{15}
}

func (x *SourceAuthCommitQueryResponse) GetCommits() []*SourceAuthCommit {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *SourceAuthCommitQueryResponse) GetOuts() *OutResponse {
	if x != nil {
		return x.Outs
	}
	return nil
}

var File_v1_suite_suite_source_auth_proto protoreflect.FileDescriptor

var file_v1_suite_suite_source_auth_proto_rawDesc = []byte{
	0x0a, 0x20, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65,
	0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74,
	0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2f, 0x6d, 0x65, 0x74,
	0x61, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x61, 0x0a, 0x14, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x33, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x1c, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73,
	0x75, 0x69, 0x74, 0x65, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x54,
	0x79, 0x70, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65,
	0x2e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6f, 0x75,
	0x74, 0x73, 0x22, 0x68, 0x0a, 0x0e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x70, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x73, 0x68, 0x55, 0x72, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x73, 0x68, 0x55, 0x72, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x69, 0x0a, 0x13,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x68, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x68, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x10, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xa5, 0x02, 0x0a,
	0x11, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x57, 0x65, 0x62, 0x68, 0x6f,
	0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x68, 0x6f, 0x6f, 0x6b, 0x55, 0x72, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x68, 0x6f, 0x6f, 0x6b, 0x55, 0x72, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6f,
	0x55, 0x72, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x55,
	0x72, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72,
	0x69, 0x67, 0x50, 0x75, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x74, 0x72,
	0x69, 0x67, 0x50, 0x75, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x69, 0x67, 0x54, 0x61,
	0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x74, 0x72, 0x69, 0x67, 0x54, 0x61, 0x67,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x69, 0x67, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x72, 0x69, 0x67, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69,
	0x74, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04,
	0x6f, 0x75, 0x74, 0x73, 0x22, 0xbb, 0x01, 0x0a, 0x0f, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41,
	0x75, 0x74, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x39, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f,
	0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x55, 0x72, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x59, 0x0a, 0x15, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68,
	0x55, 0x72, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x2e, 0x0a,
	0x04, 0x6f, 0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x22, 0xc9, 0x01,
	0x0a, 0x10, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x73, 0x49, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x69, 0x12, 0x2e, 0x0a, 0x04, 0x6f, 0x75, 0x74,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x22, 0x63, 0x0a, 0x17, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x53, 0x53, 0x48, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x71,
	0x0a, 0x19, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x53, 0x53, 0x48, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e,
	0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6f, 0x75, 0x74,
	0x73, 0x22, 0x4c, 0x0a, 0x1a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x70, 0x6f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x82, 0x01, 0x0a, 0x1b, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65,
	0x70, 0x6f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x05, 0x72,
	0x65, 0x70, 0x6f, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69,
	0x74, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04,
	0x6f, 0x75, 0x74, 0x73, 0x22, 0x4a, 0x0a, 0x16, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x70, 0x6f, 0x46, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x96, 0x01, 0x0a, 0x20, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x42,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x54, 0x61, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0a, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x54,
	0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x41, 0x75, 0x74, 0x68, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x54, 0x61, 0x67, 0x52, 0x0a, 0x62,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x54, 0x61, 0x67, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x6f, 0x75, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x1d, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73,
	0x75, 0x69, 0x74, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x2a, 0x7c, 0x0a, 0x0e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x55, 0x54, 0x48,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4f, 0x41, 0x55,
	0x54, 0x48, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f,
	0x41, 0x55, 0x54, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x10,
	0x03, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53,
	0x53, 0x48, 0x10, 0x04, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x7a, 0x6a, 0x2d, 0x73, 0x68, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_suite_suite_source_auth_proto_rawDescOnce sync.Once
	file_v1_suite_suite_source_auth_proto_rawDescData = file_v1_suite_suite_source_auth_proto_rawDesc
)

func file_v1_suite_suite_source_auth_proto_rawDescGZIP() []byte {
	file_v1_suite_suite_source_auth_proto_rawDescOnce.Do(func() {
		file_v1_suite_suite_source_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_suite_suite_source_auth_proto_rawDescData)
	})
	return file_v1_suite_suite_source_auth_proto_rawDescData
}

var file_v1_suite_suite_source_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_suite_suite_source_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_v1_suite_suite_source_auth_proto_goTypes = []interface{}{
	(SourceAuthType)(0),                      // 0: meta.v1.suite.SourceAuthType
	(*SourceAuthTypeOption)(nil),             // 1: meta.v1.suite.SourceAuthTypeOption
	(*SourceAuthTypeOptionResponse)(nil),     // 2: meta.v1.suite.SourceAuthTypeOptionResponse
	(*SourceAuthRepo)(nil),                   // 3: meta.v1.suite.SourceAuthRepo
	(*SourceAuthBranchTag)(nil),              // 4: meta.v1.suite.SourceAuthBranchTag
	(*SourceAuthCommit)(nil),                 // 5: meta.v1.suite.SourceAuthCommit
	(*SourceAuthWebhook)(nil),                // 6: meta.v1.suite.SourceAuthWebhook
	(*SourceAuthParam)(nil),                  // 7: meta.v1.suite.SourceAuthParam
	(*SourceAuthUriResponse)(nil),            // 8: meta.v1.suite.SourceAuthUriResponse
	(*SourceAuthTokens)(nil),                 // 9: meta.v1.suite.SourceAuthTokens
	(*SourceAuthSSHCredential)(nil),          // 10: meta.v1.suite.SourceAuthSSHCredential
	(*SourceAuthSSHCredentialId)(nil),        // 11: meta.v1.suite.SourceAuthSSHCredentialId
	(*SourceAuthRepoQueryRequest)(nil),       // 12: meta.v1.suite.SourceAuthRepoQueryRequest
	(*SourceAuthRepoQueryResponse)(nil),      // 13: meta.v1.suite.SourceAuthRepoQueryResponse
	(*SourceAuthRepoFullName)(nil),           // 14: meta.v1.suite.SourceAuthRepoFullName
	(*SourceAuthBranchTagQueryResponse)(nil), // 15: meta.v1.suite.SourceAuthBranchTagQueryResponse
	(*SourceAuthCommitQueryResponse)(nil),    // 16: meta.v1.suite.SourceAuthCommitQueryResponse
	(*OutResponse)(nil),                      // 17: meta.v1.suite.OutResponse
	(*timestamppb.Timestamp)(nil),            // 18: google.protobuf.Timestamp
}
var file_v1_suite_suite_source_auth_proto_depIdxs = []int32{
	0,  // 0: meta.v1.suite.SourceAuthTypeOption.value:type_name -> meta.v1.suite.SourceAuthType
	1,  // 1: meta.v1.suite.SourceAuthTypeOptionResponse.options:type_name -> meta.v1.suite.SourceAuthTypeOption
	17, // 2: meta.v1.suite.SourceAuthTypeOptionResponse.outs:type_name -> meta.v1.suite.OutResponse
	18, // 3: meta.v1.suite.SourceAuthCommit.timestamp:type_name -> google.protobuf.Timestamp
	17, // 4: meta.v1.suite.SourceAuthWebhook.outs:type_name -> meta.v1.suite.OutResponse
	0,  // 5: meta.v1.suite.SourceAuthParam.authType:type_name -> meta.v1.suite.SourceAuthType
	17, // 6: meta.v1.suite.SourceAuthUriResponse.outs:type_name -> meta.v1.suite.OutResponse
	17, // 7: meta.v1.suite.SourceAuthTokens.outs:type_name -> meta.v1.suite.OutResponse
	17, // 8: meta.v1.suite.SourceAuthSSHCredentialId.outs:type_name -> meta.v1.suite.OutResponse
	3,  // 9: meta.v1.suite.SourceAuthRepoQueryResponse.repos:type_name -> meta.v1.suite.SourceAuthRepo
	17, // 10: meta.v1.suite.SourceAuthRepoQueryResponse.outs:type_name -> meta.v1.suite.OutResponse
	4,  // 11: meta.v1.suite.SourceAuthBranchTagQueryResponse.branchTags:type_name -> meta.v1.suite.SourceAuthBranchTag
	17, // 12: meta.v1.suite.SourceAuthBranchTagQueryResponse.outs:type_name -> meta.v1.suite.OutResponse
	5,  // 13: meta.v1.suite.SourceAuthCommitQueryResponse.commits:type_name -> meta.v1.suite.SourceAuthCommit
	17, // 14: meta.v1.suite.SourceAuthCommitQueryResponse.outs:type_name -> meta.v1.suite.OutResponse
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_v1_suite_suite_source_auth_proto_init() }
func file_v1_suite_suite_source_auth_proto_init() {
	if File_v1_suite_suite_source_auth_proto != nil {
		return
	}
	file_v1_suite_meta_running_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_suite_suite_source_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthTypeOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthTypeOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthRepo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthBranchTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthCommit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthWebhook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthUriResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthTokens); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthSSHCredential); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthSSHCredentialId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthRepoQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthRepoQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthRepoFullName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthBranchTagQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_source_auth_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceAuthCommitQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_suite_suite_source_auth_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_suite_suite_source_auth_proto_goTypes,
		DependencyIndexes: file_v1_suite_suite_source_auth_proto_depIdxs,
		EnumInfos:         file_v1_suite_suite_source_auth_proto_enumTypes,
		MessageInfos:      file_v1_suite_suite_source_auth_proto_msgTypes,
	}.Build()
	File_v1_suite_suite_source_auth_proto = out.File
	file_v1_suite_suite_source_auth_proto_rawDesc = nil
	file_v1_suite_suite_source_auth_proto_goTypes = nil
	file_v1_suite_suite_source_auth_proto_depIdxs = nil
}
