// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: v1/suite/suite_issues.proto

package suite

import (
	base "github.com/zj-sh/meta/v1/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssuesParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params   *base.JsonString `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	To       *base.Userinfo   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	At       []*base.Userinfo `protobuf:"bytes,3,rep,name=at,proto3" json:"at,omitempty"`
	Title    string           `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                       // issue的标题
	RichText string           `protobuf:"bytes,5,opt,name=rich_text,json=richText,proto3" json:"rich_text,omitempty"` // issue的富文本（rich_text == markdown == content）
	Markdown string           `protobuf:"bytes,6,opt,name=markdown,proto3" json:"markdown,omitempty"`                 // issue的markdown（rich_text == markdown == content）
	Content  string           `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`                   // issue的内容纯文本（rich_text == markdown == content）
	Url      string           `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`                           // issue的url，如果有值说明可以支持跳转
}

func (x *IssuesParam) Reset() {
	*x = IssuesParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_issues_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssuesParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuesParam) ProtoMessage() {}

func (x *IssuesParam) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_issues_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuesParam.ProtoReflect.Descriptor instead.
func (*IssuesParam) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_issues_proto_rawDescGZIP(), []int{0}
}

func (x *IssuesParam) GetParams() *base.JsonString {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *IssuesParam) GetTo() *base.Userinfo {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *IssuesParam) GetAt() []*base.Userinfo {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *IssuesParam) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IssuesParam) GetRichText() string {
	if x != nil {
		return x.RichText
	}
	return ""
}

func (x *IssuesParam) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *IssuesParam) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IssuesParam) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_v1_suite_suite_issues_proto protoreflect.FileDescriptor

var file_v1_suite_suite_issues_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65,
	0x5f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d,
	0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x1a, 0x12, 0x76, 0x31,
	0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x16, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x6f,
	0x72, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x02, 0x0a, 0x0b, 0x49, 0x73, 0x73,
	0x75, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x26, 0x0a, 0x02, 0x74, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x26, 0x0a, 0x02, 0x61, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x02, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x69, 0x63, 0x68, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x69, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x6d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x6a, 0x2d, 0x73, 0x68, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_suite_suite_issues_proto_rawDescOnce sync.Once
	file_v1_suite_suite_issues_proto_rawDescData = file_v1_suite_suite_issues_proto_rawDesc
)

func file_v1_suite_suite_issues_proto_rawDescGZIP() []byte {
	file_v1_suite_suite_issues_proto_rawDescOnce.Do(func() {
		file_v1_suite_suite_issues_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_suite_suite_issues_proto_rawDescData)
	})
	return file_v1_suite_suite_issues_proto_rawDescData
}

var file_v1_suite_suite_issues_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_suite_suite_issues_proto_goTypes = []interface{}{
	(*IssuesParam)(nil),     // 0: meta.v1.suite.IssuesParam
	(*base.JsonString)(nil), // 1: meta.v1.base.JsonString
	(*base.Userinfo)(nil),   // 2: meta.v1.base.Userinfo
}
var file_v1_suite_suite_issues_proto_depIdxs = []int32{
	1, // 0: meta.v1.suite.IssuesParam.params:type_name -> meta.v1.base.JsonString
	2, // 1: meta.v1.suite.IssuesParam.to:type_name -> meta.v1.base.Userinfo
	2, // 2: meta.v1.suite.IssuesParam.at:type_name -> meta.v1.base.Userinfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_suite_suite_issues_proto_init() }
func file_v1_suite_suite_issues_proto_init() {
	if File_v1_suite_suite_issues_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_suite_suite_issues_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IssuesParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_suite_suite_issues_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_suite_suite_issues_proto_goTypes,
		DependencyIndexes: file_v1_suite_suite_issues_proto_depIdxs,
		MessageInfos:      file_v1_suite_suite_issues_proto_msgTypes,
	}.Build()
	File_v1_suite_suite_issues_proto = out.File
	file_v1_suite_suite_issues_proto_rawDesc = nil
	file_v1_suite_suite_issues_proto_goTypes = nil
	file_v1_suite_suite_issues_proto_depIdxs = nil
}
