// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: v1/suite/suite_product.proto

package suite

import (
	base "github.com/zj-sh/meta/v1/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductUploadStreamParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params     *base.JsonString `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	PkgName    string           `protobuf:"bytes,2,opt,name=pkg_name,json=pkgName,proto3" json:"pkg_name,omitempty"`
	PkgVersion string           `protobuf:"bytes,3,opt,name=pkg_version,json=pkgVersion,proto3" json:"pkg_version,omitempty"`
	PkgSize    int64            `protobuf:"varint,4,opt,name=pkg_size,json=pkgSize,proto3" json:"pkg_size,omitempty"`
	Md5        string           `protobuf:"bytes,5,opt,name=md5,proto3" json:"md5,omitempty"`
	Size       int64            `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Byte       []byte           `protobuf:"bytes,7,opt,name=byte,proto3" json:"byte,omitempty"`
	Done       bool             `protobuf:"varint,8,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *ProductUploadStreamParam) Reset() {
	*x = ProductUploadStreamParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_product_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductUploadStreamParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUploadStreamParam) ProtoMessage() {}

func (x *ProductUploadStreamParam) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_product_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUploadStreamParam.ProtoReflect.Descriptor instead.
func (*ProductUploadStreamParam) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductUploadStreamParam) GetParams() *base.JsonString {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ProductUploadStreamParam) GetPkgName() string {
	if x != nil {
		return x.PkgName
	}
	return ""
}

func (x *ProductUploadStreamParam) GetPkgVersion() string {
	if x != nil {
		return x.PkgVersion
	}
	return ""
}

func (x *ProductUploadStreamParam) GetPkgSize() int64 {
	if x != nil {
		return x.PkgSize
	}
	return 0
}

func (x *ProductUploadStreamParam) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *ProductUploadStreamParam) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ProductUploadStreamParam) GetByte() []byte {
	if x != nil {
		return x.Byte
	}
	return nil
}

func (x *ProductUploadStreamParam) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type ProductUploadFileParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params     *base.JsonString `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	PkgName    string           `protobuf:"bytes,2,opt,name=pkg_name,json=pkgName,proto3" json:"pkg_name,omitempty"`
	PkgVersion string           `protobuf:"bytes,3,opt,name=pkg_version,json=pkgVersion,proto3" json:"pkg_version,omitempty"`
	Filepath   string           `protobuf:"bytes,4,opt,name=filepath,proto3" json:"filepath,omitempty"`
}

func (x *ProductUploadFileParam) Reset() {
	*x = ProductUploadFileParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_product_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductUploadFileParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUploadFileParam) ProtoMessage() {}

func (x *ProductUploadFileParam) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_product_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUploadFileParam.ProtoReflect.Descriptor instead.
func (*ProductUploadFileParam) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductUploadFileParam) GetParams() *base.JsonString {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ProductUploadFileParam) GetPkgName() string {
	if x != nil {
		return x.PkgName
	}
	return ""
}

func (x *ProductUploadFileParam) GetPkgVersion() string {
	if x != nil {
		return x.PkgVersion
	}
	return ""
}

func (x *ProductUploadFileParam) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

type ProductUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status  base.RunStatus `protobuf:"varint,2,opt,name=status,proto3,enum=meta.v1.base.RunStatus" json:"status,omitempty"`
	Message string         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Outs    *OutResponse   `protobuf:"bytes,4,opt,name=outs,proto3" json:"outs,omitempty"`
}

func (x *ProductUploadResponse) Reset() {
	*x = ProductUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_product_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUploadResponse) ProtoMessage() {}

func (x *ProductUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_product_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUploadResponse.ProtoReflect.Descriptor instead.
func (*ProductUploadResponse) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductUploadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductUploadResponse) GetStatus() base.RunStatus {
	if x != nil {
		return x.Status
	}
	return base.RunStatus(0)
}

func (x *ProductUploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProductUploadResponse) GetOuts() *OutResponse {
	if x != nil {
		return x.Outs
	}
	return nil
}

type ProductDeleteParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *base.JsonString `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Id     string           `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ProductDeleteParam) Reset() {
	*x = ProductDeleteParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_product_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductDeleteParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDeleteParam) ProtoMessage() {}

func (x *ProductDeleteParam) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_product_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDeleteParam.ProtoReflect.Descriptor instead.
func (*ProductDeleteParam) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductDeleteParam) GetParams() *base.JsonString {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ProductDeleteParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_v1_suite_suite_product_proto protoreflect.FileDescriptor

var file_v1_suite_suite_product_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65,
	0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x1a, 0x12, 0x76,
	0x31, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61,
	0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf1,
	0x01, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x30, 0x0a, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x70, 0x6b, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x6b, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6b, 0x67, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x6b, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6b, 0x67,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x6b, 0x67,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x79,
	0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x79, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f,
	0x6e, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x30, 0x0a,
	0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4a, 0x73, 0x6f,
	0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x19, 0x0a, 0x08, 0x70, 0x6b, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x6b, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6b,
	0x67, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x6b, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x22, 0xa2, 0x01, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x04,
	0x6f, 0x75, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x22, 0x56, 0x0a, 0x12,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x7a, 0x6a, 0x2d, 0x73, 0x68, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_suite_suite_product_proto_rawDescOnce sync.Once
	file_v1_suite_suite_product_proto_rawDescData = file_v1_suite_suite_product_proto_rawDesc
)

func file_v1_suite_suite_product_proto_rawDescGZIP() []byte {
	file_v1_suite_suite_product_proto_rawDescOnce.Do(func() {
		file_v1_suite_suite_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_suite_suite_product_proto_rawDescData)
	})
	return file_v1_suite_suite_product_proto_rawDescData
}

var file_v1_suite_suite_product_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_suite_suite_product_proto_goTypes = []interface{}{
	(*ProductUploadStreamParam)(nil), // 0: meta.v1.suite.ProductUploadStreamParam
	(*ProductUploadFileParam)(nil),   // 1: meta.v1.suite.ProductUploadFileParam
	(*ProductUploadResponse)(nil),    // 2: meta.v1.suite.ProductUploadResponse
	(*ProductDeleteParam)(nil),       // 3: meta.v1.suite.ProductDeleteParam
	(*base.JsonString)(nil),          // 4: meta.v1.base.JsonString
	(base.RunStatus)(0),              // 5: meta.v1.base.RunStatus
	(*OutResponse)(nil),              // 6: meta.v1.suite.OutResponse
}
var file_v1_suite_suite_product_proto_depIdxs = []int32{
	4, // 0: meta.v1.suite.ProductUploadStreamParam.params:type_name -> meta.v1.base.JsonString
	4, // 1: meta.v1.suite.ProductUploadFileParam.params:type_name -> meta.v1.base.JsonString
	5, // 2: meta.v1.suite.ProductUploadResponse.status:type_name -> meta.v1.base.RunStatus
	6, // 3: meta.v1.suite.ProductUploadResponse.outs:type_name -> meta.v1.suite.OutResponse
	4, // 4: meta.v1.suite.ProductDeleteParam.params:type_name -> meta.v1.base.JsonString
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_suite_suite_product_proto_init() }
func file_v1_suite_suite_product_proto_init() {
	if File_v1_suite_suite_product_proto != nil {
		return
	}
	file_v1_suite_meta_running_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_suite_suite_product_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductUploadStreamParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_product_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductUploadFileParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_product_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_product_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductDeleteParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_suite_suite_product_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_suite_suite_product_proto_goTypes,
		DependencyIndexes: file_v1_suite_suite_product_proto_depIdxs,
		MessageInfos:      file_v1_suite_suite_product_proto_msgTypes,
	}.Build()
	File_v1_suite_suite_product_proto = out.File
	file_v1_suite_suite_product_proto_rawDesc = nil
	file_v1_suite_suite_product_proto_goTypes = nil
	file_v1_suite_suite_product_proto_depIdxs = nil
}
