// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: v1/suite/suite_build.proto

package suite

import (
	base "github.com/zj-sh/meta/v1/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildType int32

const (
	BuildType_BUILD_TYPE_UNKNOWN    BuildType = 0
	BuildType_BUILD_TYPE_IN_IMAGE   BuildType = 1 // 镜像内构建
	BuildType_BUILD_TYPE_IN_MACHINE BuildType = 2 // 机器内构建
)

// Enum value maps for BuildType.
var (
	BuildType_name = map[int32]string{
		0: "BUILD_TYPE_UNKNOWN",
		1: "BUILD_TYPE_IN_IMAGE",
		2: "BUILD_TYPE_IN_MACHINE",
	}
	BuildType_value = map[string]int32{
		"BUILD_TYPE_UNKNOWN":    0,
		"BUILD_TYPE_IN_IMAGE":   1,
		"BUILD_TYPE_IN_MACHINE": 2,
	}
)

func (x BuildType) Enum() *BuildType {
	p := new(BuildType)
	*p = x
	return p
}

func (x BuildType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_suite_suite_build_proto_enumTypes[0].Descriptor()
}

func (BuildType) Type() protoreflect.EnumType {
	return &file_v1_suite_suite_build_proto_enumTypes[0]
}

func (x BuildType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildType.Descriptor instead.
func (BuildType) EnumDescriptor() ([]byte, []int) {
	return file_v1_suite_suite_build_proto_rawDescGZIP(), []int{0}
}

type BuildParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params       *base.JsonString `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`                                                      // go build -o app
	BuildType    BuildType        `protobuf:"varint,2,opt,name=build_type,json=buildType,proto3,enum=meta.v1.suite.BuildType" json:"build_type,omitempty"` // 构建类型
	BuildIn      string           `protobuf:"bytes,3,opt,name=build_in,json=buildIn,proto3" json:"build_in,omitempty"`                                     // 构建基座，如果类型是BUILD_TYPE_IN_IMAGE，则为镜像名，如果类型是BUILD_TYPE_IN_MACHINE，则为机器ID
	BuildOutPath string           `protobuf:"bytes,4,opt,name=build_out_path,json=buildOutPath,proto3" json:"build_out_path,omitempty"`                    // 构建物路径
}

func (x *BuildParam) Reset() {
	*x = BuildParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_build_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildParam) ProtoMessage() {}

func (x *BuildParam) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_build_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildParam.ProtoReflect.Descriptor instead.
func (*BuildParam) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_build_proto_rawDescGZIP(), []int{0}
}

func (x *BuildParam) GetParams() *base.JsonString {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *BuildParam) GetBuildType() BuildType {
	if x != nil {
		return x.BuildType
	}
	return BuildType_BUILD_TYPE_UNKNOWN
}

func (x *BuildParam) GetBuildIn() string {
	if x != nil {
		return x.BuildIn
	}
	return ""
}

func (x *BuildParam) GetBuildOutPath() string {
	if x != nil {
		return x.BuildOutPath
	}
	return ""
}

type BuildResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  base.RunStatus `protobuf:"varint,1,opt,name=status,proto3,enum=meta.v1.base.RunStatus" json:"status,omitempty"` // 运行状态
	Log     *base.Log      `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	Message string         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Outs    *OutResponse   `protobuf:"bytes,4,opt,name=outs,proto3" json:"outs,omitempty"`
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_build_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_build_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_build_proto_rawDescGZIP(), []int{1}
}

func (x *BuildResponse) GetStatus() base.RunStatus {
	if x != nil {
		return x.Status
	}
	return base.RunStatus(0)
}

func (x *BuildResponse) GetLog() *base.Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *BuildResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuildResponse) GetOuts() *OutResponse {
	if x != nil {
		return x.Outs
	}
	return nil
}

type BuildMachineParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmdId    string `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`           // 命令id
	Cmd      string `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`                            // 命令
	Timeout  int64  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`                   // 超时时间
	IsCancel bool   `protobuf:"varint,4,opt,name=is_cancel,json=isCancel,proto3" json:"is_cancel,omitempty"` // 是否取消
}

func (x *BuildMachineParam) Reset() {
	*x = BuildMachineParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_build_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildMachineParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildMachineParam) ProtoMessage() {}

func (x *BuildMachineParam) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_build_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildMachineParam.ProtoReflect.Descriptor instead.
func (*BuildMachineParam) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_build_proto_rawDescGZIP(), []int{2}
}

func (x *BuildMachineParam) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *BuildMachineParam) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *BuildMachineParam) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *BuildMachineParam) GetIsCancel() bool {
	if x != nil {
		return x.IsCancel
	}
	return false
}

type BuildMachineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmdId  string `protobuf:"bytes,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`     // 命令id
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                // 结果
	IsDone bool   `protobuf:"varint,3,opt,name=is_done,json=isDone,proto3" json:"is_done,omitempty"` // 是否结束，只对应此id，并非全部结束
}

func (x *BuildMachineResponse) Reset() {
	*x = BuildMachineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_build_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildMachineResponse) ProtoMessage() {}

func (x *BuildMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_build_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildMachineResponse.ProtoReflect.Descriptor instead.
func (*BuildMachineResponse) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_build_proto_rawDescGZIP(), []int{3}
}

func (x *BuildMachineResponse) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *BuildMachineResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *BuildMachineResponse) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

var File_v1_suite_suite_build_proto protoreflect.FileDescriptor

var file_v1_suite_suite_build_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65,
	0x5f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x1a, 0x12, 0x76, 0x31, 0x2f,
	0x62, 0x61, 0x73, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x16, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x6c, 0x6f,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x69, 0x74,
	0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x01, 0x0a, 0x0a, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x37, 0x0a, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x6f, 0x75, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x4f, 0x75, 0x74, 0x50, 0x61, 0x74, 0x68, 0x22,
	0xaf, 0x01, 0x0a, 0x0d, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x23, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4c,
	0x6f, 0x67, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x2e, 0x0a, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e,
	0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6f, 0x75, 0x74,
	0x73, 0x22, 0x73, 0x0a, 0x11, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x6d, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f,
	0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x22, 0x5e, 0x0a, 0x14, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15,
	0x0a, 0x06, 0x63, 0x6d, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x63, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x69, 0x73, 0x5f, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x69, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x2a, 0x57, 0x0a, 0x09, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x42,
	0x55, 0x49, 0x4c, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x5f, 0x49, 0x4d, 0x41,
	0x47, 0x45, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x49, 0x4e, 0x5f, 0x4d, 0x41, 0x43, 0x48, 0x49, 0x4e, 0x45, 0x10, 0x02, 0x42,
	0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x6a,
	0x2d, 0x73, 0x68, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x69, 0x74,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_suite_suite_build_proto_rawDescOnce sync.Once
	file_v1_suite_suite_build_proto_rawDescData = file_v1_suite_suite_build_proto_rawDesc
)

func file_v1_suite_suite_build_proto_rawDescGZIP() []byte {
	file_v1_suite_suite_build_proto_rawDescOnce.Do(func() {
		file_v1_suite_suite_build_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_suite_suite_build_proto_rawDescData)
	})
	return file_v1_suite_suite_build_proto_rawDescData
}

var file_v1_suite_suite_build_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_suite_suite_build_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_suite_suite_build_proto_goTypes = []interface{}{
	(BuildType)(0),               // 0: meta.v1.suite.BuildType
	(*BuildParam)(nil),           // 1: meta.v1.suite.BuildParam
	(*BuildResponse)(nil),        // 2: meta.v1.suite.BuildResponse
	(*BuildMachineParam)(nil),    // 3: meta.v1.suite.BuildMachineParam
	(*BuildMachineResponse)(nil), // 4: meta.v1.suite.BuildMachineResponse
	(*base.JsonString)(nil),      // 5: meta.v1.base.JsonString
	(base.RunStatus)(0),          // 6: meta.v1.base.RunStatus
	(*base.Log)(nil),             // 7: meta.v1.base.Log
	(*OutResponse)(nil),          // 8: meta.v1.suite.OutResponse
}
var file_v1_suite_suite_build_proto_depIdxs = []int32{
	5, // 0: meta.v1.suite.BuildParam.params:type_name -> meta.v1.base.JsonString
	0, // 1: meta.v1.suite.BuildParam.build_type:type_name -> meta.v1.suite.BuildType
	6, // 2: meta.v1.suite.BuildResponse.status:type_name -> meta.v1.base.RunStatus
	7, // 3: meta.v1.suite.BuildResponse.log:type_name -> meta.v1.base.Log
	8, // 4: meta.v1.suite.BuildResponse.outs:type_name -> meta.v1.suite.OutResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_suite_suite_build_proto_init() }
func file_v1_suite_suite_build_proto_init() {
	if File_v1_suite_suite_build_proto != nil {
		return
	}
	file_v1_suite_meta_running_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_suite_suite_build_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_build_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_build_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildMachineParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_build_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildMachineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_suite_suite_build_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_suite_suite_build_proto_goTypes,
		DependencyIndexes: file_v1_suite_suite_build_proto_depIdxs,
		EnumInfos:         file_v1_suite_suite_build_proto_enumTypes,
		MessageInfos:      file_v1_suite_suite_build_proto_msgTypes,
	}.Build()
	File_v1_suite_suite_build_proto = out.File
	file_v1_suite_suite_build_proto_rawDesc = nil
	file_v1_suite_suite_build_proto_goTypes = nil
	file_v1_suite_suite_build_proto_depIdxs = nil
}
