// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: v1/suite/suite_approval.proto

package suite

import (
	base "github.com/zj-sh/meta/v1/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApprovalSendParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *base.JsonString `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Email  string           `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone  string           `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *ApprovalSendParam) Reset() {
	*x = ApprovalSendParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_approval_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApprovalSendParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalSendParam) ProtoMessage() {}

func (x *ApprovalSendParam) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_approval_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalSendParam.ProtoReflect.Descriptor instead.
func (*ApprovalSendParam) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_approval_proto_rawDescGZIP(), []int{0}
}

func (x *ApprovalSendParam) GetParams() *base.JsonString {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ApprovalSendParam) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ApprovalSendParam) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ApprovalSendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Outs *OutResponse `protobuf:"bytes,2,opt,name=outs,proto3" json:"outs,omitempty"`
}

func (x *ApprovalSendResponse) Reset() {
	*x = ApprovalSendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_approval_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApprovalSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalSendResponse) ProtoMessage() {}

func (x *ApprovalSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_approval_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalSendResponse.ProtoReflect.Descriptor instead.
func (*ApprovalSendResponse) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_approval_proto_rawDescGZIP(), []int{1}
}

func (x *ApprovalSendResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApprovalSendResponse) GetOuts() *OutResponse {
	if x != nil {
		return x.Outs
	}
	return nil
}

type ApprovalCancelParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *base.JsonString `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Id     string           `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ApprovalCancelParam) Reset() {
	*x = ApprovalCancelParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_approval_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApprovalCancelParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalCancelParam) ProtoMessage() {}

func (x *ApprovalCancelParam) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_approval_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalCancelParam.ProtoReflect.Descriptor instead.
func (*ApprovalCancelParam) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_approval_proto_rawDescGZIP(), []int{2}
}

func (x *ApprovalCancelParam) GetParams() *base.JsonString {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ApprovalCancelParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_v1_suite_suite_approval_proto protoreflect.FileDescriptor

var file_v1_suite_suite_approval_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65,
	0x5f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x1a, 0x12,
	0x76, 0x31, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2f, 0x6d, 0x65, 0x74,
	0x61, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x71, 0x0a, 0x11, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x53, 0x65, 0x6e, 0x64, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x06,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x22, 0x56, 0x0a, 0x14, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x53, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x6f, 0x75,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x22, 0x57, 0x0a, 0x13, 0x41, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x7a, 0x6a, 0x2d, 0x73, 0x68, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x75, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_suite_suite_approval_proto_rawDescOnce sync.Once
	file_v1_suite_suite_approval_proto_rawDescData = file_v1_suite_suite_approval_proto_rawDesc
)

func file_v1_suite_suite_approval_proto_rawDescGZIP() []byte {
	file_v1_suite_suite_approval_proto_rawDescOnce.Do(func() {
		file_v1_suite_suite_approval_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_suite_suite_approval_proto_rawDescData)
	})
	return file_v1_suite_suite_approval_proto_rawDescData
}

var file_v1_suite_suite_approval_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_suite_suite_approval_proto_goTypes = []interface{}{
	(*ApprovalSendParam)(nil),    // 0: meta.v1.suite.ApprovalSendParam
	(*ApprovalSendResponse)(nil), // 1: meta.v1.suite.ApprovalSendResponse
	(*ApprovalCancelParam)(nil),  // 2: meta.v1.suite.ApprovalCancelParam
	(*base.JsonString)(nil),      // 3: meta.v1.base.JsonString
	(*OutResponse)(nil),          // 4: meta.v1.suite.OutResponse
}
var file_v1_suite_suite_approval_proto_depIdxs = []int32{
	3, // 0: meta.v1.suite.ApprovalSendParam.params:type_name -> meta.v1.base.JsonString
	4, // 1: meta.v1.suite.ApprovalSendResponse.outs:type_name -> meta.v1.suite.OutResponse
	3, // 2: meta.v1.suite.ApprovalCancelParam.params:type_name -> meta.v1.base.JsonString
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_suite_suite_approval_proto_init() }
func file_v1_suite_suite_approval_proto_init() {
	if File_v1_suite_suite_approval_proto != nil {
		return
	}
	file_v1_suite_meta_running_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_suite_suite_approval_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApprovalSendParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_approval_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApprovalSendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_approval_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApprovalCancelParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_suite_suite_approval_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_suite_suite_approval_proto_goTypes,
		DependencyIndexes: file_v1_suite_suite_approval_proto_depIdxs,
		MessageInfos:      file_v1_suite_suite_approval_proto_msgTypes,
	}.Build()
	File_v1_suite_suite_approval_proto = out.File
	file_v1_suite_suite_approval_proto_rawDesc = nil
	file_v1_suite_suite_approval_proto_goTypes = nil
	file_v1_suite_suite_approval_proto_depIdxs = nil
}
