// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: v1/suite/suite_pipe.proto

package suite

import (
	base "github.com/zj-sh/meta/v1/base"
	pipe "github.com/zj-sh/meta/v1/pipe"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PipelineRunParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params     *base.JsonString `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	PipelineId string           `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Vars       []*pipe.Var      `protobuf:"bytes,3,rep,name=vars,proto3" json:"vars,omitempty"`
}

func (x *PipelineRunParam) Reset() {
	*x = PipelineRunParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_pipe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineRunParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineRunParam) ProtoMessage() {}

func (x *PipelineRunParam) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_pipe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineRunParam.ProtoReflect.Descriptor instead.
func (*PipelineRunParam) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_pipe_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineRunParam) GetParams() *base.JsonString {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *PipelineRunParam) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineRunParam) GetVars() []*pipe.Var {
	if x != nil {
		return x.Vars
	}
	return nil
}

type PipelineRunResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PipelineId string       `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	BuildId    string       `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Outs       *OutResponse `protobuf:"bytes,3,opt,name=outs,proto3" json:"outs,omitempty"`
}

func (x *PipelineRunResponse) Reset() {
	*x = PipelineRunResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_pipe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineRunResponse) ProtoMessage() {}

func (x *PipelineRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_pipe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineRunResponse.ProtoReflect.Descriptor instead.
func (*PipelineRunResponse) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_pipe_proto_rawDescGZIP(), []int{1}
}

func (x *PipelineRunResponse) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineRunResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *PipelineRunResponse) GetOuts() *OutResponse {
	if x != nil {
		return x.Outs
	}
	return nil
}

type PipelineCancelParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params     *base.JsonString `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	PipelineId string           `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	BuildId    string           `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
}

func (x *PipelineCancelParam) Reset() {
	*x = PipelineCancelParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_suite_suite_pipe_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineCancelParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineCancelParam) ProtoMessage() {}

func (x *PipelineCancelParam) ProtoReflect() protoreflect.Message {
	mi := &file_v1_suite_suite_pipe_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineCancelParam.ProtoReflect.Descriptor instead.
func (*PipelineCancelParam) Descriptor() ([]byte, []int) {
	return file_v1_suite_suite_pipe_proto_rawDescGZIP(), []int{2}
}

func (x *PipelineCancelParam) GetParams() *base.JsonString {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *PipelineCancelParam) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineCancelParam) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

var File_v1_suite_suite_pipe_proto protoreflect.FileDescriptor

var file_v1_suite_suite_pipe_proto_rawDesc = []byte{
	0x0a, 0x19, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2f, 0x73, 0x75, 0x69, 0x74, 0x65,
	0x5f, 0x70, 0x69, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x1a, 0x12, 0x76, 0x31, 0x2f, 0x62,
	0x61, 0x73, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x76, 0x31, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x5f, 0x76, 0x61, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x76, 0x31, 0x2f,
	0x73, 0x75, 0x69, 0x74, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x10, 0x50, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x75, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x30, 0x0a,
	0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4a, 0x73, 0x6f,
	0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64,
	0x12, 0x25, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x2e, 0x56, 0x61,
	0x72, 0x52, 0x04, 0x76, 0x61, 0x72, 0x73, 0x22, 0x81, 0x01, 0x0a, 0x13, 0x50, 0x69, 0x70, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x6f,
	0x75, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x6f, 0x75, 0x74, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x13,
	0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x69, 0x70, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x64, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x7a, 0x6a, 0x2d, 0x73, 0x68, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x75,
	0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_suite_suite_pipe_proto_rawDescOnce sync.Once
	file_v1_suite_suite_pipe_proto_rawDescData = file_v1_suite_suite_pipe_proto_rawDesc
)

func file_v1_suite_suite_pipe_proto_rawDescGZIP() []byte {
	file_v1_suite_suite_pipe_proto_rawDescOnce.Do(func() {
		file_v1_suite_suite_pipe_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_suite_suite_pipe_proto_rawDescData)
	})
	return file_v1_suite_suite_pipe_proto_rawDescData
}

var file_v1_suite_suite_pipe_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_suite_suite_pipe_proto_goTypes = []interface{}{
	(*PipelineRunParam)(nil),    // 0: meta.v1.suite.PipelineRunParam
	(*PipelineRunResponse)(nil), // 1: meta.v1.suite.PipelineRunResponse
	(*PipelineCancelParam)(nil), // 2: meta.v1.suite.PipelineCancelParam
	(*base.JsonString)(nil),     // 3: meta.v1.base.JsonString
	(*pipe.Var)(nil),            // 4: meta.v1.pipe.Var
	(*OutResponse)(nil),         // 5: meta.v1.suite.OutResponse
}
var file_v1_suite_suite_pipe_proto_depIdxs = []int32{
	3, // 0: meta.v1.suite.PipelineRunParam.params:type_name -> meta.v1.base.JsonString
	4, // 1: meta.v1.suite.PipelineRunParam.vars:type_name -> meta.v1.pipe.Var
	5, // 2: meta.v1.suite.PipelineRunResponse.outs:type_name -> meta.v1.suite.OutResponse
	3, // 3: meta.v1.suite.PipelineCancelParam.params:type_name -> meta.v1.base.JsonString
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_suite_suite_pipe_proto_init() }
func file_v1_suite_suite_pipe_proto_init() {
	if File_v1_suite_suite_pipe_proto != nil {
		return
	}
	file_v1_suite_meta_running_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_suite_suite_pipe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineRunParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_pipe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineRunResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_suite_suite_pipe_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineCancelParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_suite_suite_pipe_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_suite_suite_pipe_proto_goTypes,
		DependencyIndexes: file_v1_suite_suite_pipe_proto_depIdxs,
		MessageInfos:      file_v1_suite_suite_pipe_proto_msgTypes,
	}.Build()
	File_v1_suite_suite_pipe_proto = out.File
	file_v1_suite_suite_pipe_proto_rawDesc = nil
	file_v1_suite_suite_pipe_proto_goTypes = nil
	file_v1_suite_suite_pipe_proto_depIdxs = nil
}
