// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: v1/base/meta_pipeline.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildArch int32

const (
	BuildArch_BUILD_ARCH_UNSPECIFIED BuildArch = 0
	BuildArch_BUILD_ARCH_AMD64       BuildArch = 1
	BuildArch_BUILD_ARCH_ARM64       BuildArch = 2
)

// Enum value maps for BuildArch.
var (
	BuildArch_name = map[int32]string{
		0: "BUILD_ARCH_UNSPECIFIED",
		1: "BUILD_ARCH_AMD64",
		2: "BUILD_ARCH_ARM64",
	}
	BuildArch_value = map[string]int32{
		"BUILD_ARCH_UNSPECIFIED": 0,
		"BUILD_ARCH_AMD64":       1,
		"BUILD_ARCH_ARM64":       2,
	}
)

func (x BuildArch) Enum() *BuildArch {
	p := new(BuildArch)
	*p = x
	return p
}

func (x BuildArch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildArch) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_base_meta_pipeline_proto_enumTypes[0].Descriptor()
}

func (BuildArch) Type() protoreflect.EnumType {
	return &file_v1_base_meta_pipeline_proto_enumTypes[0]
}

func (x BuildArch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildArch.Descriptor instead.
func (BuildArch) EnumDescriptor() ([]byte, []int) {
	return file_v1_base_meta_pipeline_proto_rawDescGZIP(), []int{0}
}

var File_v1_base_meta_pipeline_proto protoreflect.FileDescriptor

var file_v1_base_meta_pipeline_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x70,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d,
	0x65, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2a, 0x53, 0x0a, 0x09, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x41, 0x72, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x16, 0x42, 0x55, 0x49, 0x4c,
	0x44, 0x5f, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x5f, 0x41, 0x52,
	0x43, 0x48, 0x5f, 0x41, 0x4d, 0x44, 0x36, 0x34, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x42, 0x55,
	0x49, 0x4c, 0x44, 0x5f, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x41, 0x52, 0x4d, 0x36, 0x34, 0x10, 0x02,
	0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a,
	0x6a, 0x2d, 0x73, 0x68, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_base_meta_pipeline_proto_rawDescOnce sync.Once
	file_v1_base_meta_pipeline_proto_rawDescData = file_v1_base_meta_pipeline_proto_rawDesc
)

func file_v1_base_meta_pipeline_proto_rawDescGZIP() []byte {
	file_v1_base_meta_pipeline_proto_rawDescOnce.Do(func() {
		file_v1_base_meta_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_base_meta_pipeline_proto_rawDescData)
	})
	return file_v1_base_meta_pipeline_proto_rawDescData
}

var file_v1_base_meta_pipeline_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_base_meta_pipeline_proto_goTypes = []interface{}{
	(BuildArch)(0), // 0: meta.v1.base.BuildArch
}
var file_v1_base_meta_pipeline_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_base_meta_pipeline_proto_init() }
func file_v1_base_meta_pipeline_proto_init() {
	if File_v1_base_meta_pipeline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_base_meta_pipeline_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_base_meta_pipeline_proto_goTypes,
		DependencyIndexes: file_v1_base_meta_pipeline_proto_depIdxs,
		EnumInfos:         file_v1_base_meta_pipeline_proto_enumTypes,
	}.Build()
	File_v1_base_meta_pipeline_proto = out.File
	file_v1_base_meta_pipeline_proto_rawDesc = nil
	file_v1_base_meta_pipeline_proto_goTypes = nil
	file_v1_base_meta_pipeline_proto_depIdxs = nil
}
